Extra translateables
DrVrej/VJ-Base pull request #38
Opened 2021-05-07 06:59 UTC by Blueberryy

2021-05-07 18:19 UTC, DrVrej commented on lua/autorun/vj_globals.lua
> +function VJ_PICK(tbl) -- Needs to be edited a bit to use whole line as phrase
Not sure what this means?

2021-05-07 18:38 UTC, DrVrej commented on lua/autorun/vj_menu_spawninfo.lua
> +VJ.AddEntity("FirePlace","sent_vj_fireplace","DrVrej",false,0,true,vCat)
Fireplace is the correct English word

2021-05-07 18:39 UTC, DrVrej commented on lua/autorun/vj_menu_spawninfo.lua
> +VJ.AddCategoryInfo("#vjbase.menu.tabs.zombies", {Icon = "vj_base/icons/zombies.png"})
These changes will broke many NPC packs

2021-05-07 18:45 UTC, DrVrej requested changes
To many issues in these changes, broke way to many plugins and to many files to review at once.

2021-05-08 08:53 UTC, Blueberryy commented
Thank youf or the fix!

2021-05-27 19:29 UTC, closed without merging